name: Build, Test, and Analyze

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install Clippy
      run: rustup component add clippy
    - name: Build Project
      run: cargo build --release
    - name: Test Project
      run: cargo test
    - name: Analyze with Clippy
      run: cargo clippy