name: Build, Test, Analyze and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install Clippy
      run: rustup component add clippy
    - name: Build Project
      run: cargo build --release
    - name: Test Project
      run: cargo test
    - name: Analyze with Clippy
      run: cargo clippy
    - name: Create artifacts directory
      run: mkdir artifacts
    - name: Copy artifacts
      run: cp target/release/verb_memorizer_beta artifacts/ | zip -r linux.zip artifacts
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./linux.zip
        asset_name: linux.zip
        asset_content_type: application/zip
